eureka:
  client:
    healthcheck:
      enabled: true

owms:
  partners:
    sps01: tcpip-palett1
    sps02: tcpip-palett2

---
spring:
  profiles: ASYNCHRONOUS

owms:
  driver:
    osip:
      enabled: true
    locu:
      queue-name: locu
      exchange-name: osip
      routing-key: osip.locu.received
    sysu:
      queue-name: sysu
      exchange-name: osip
      routing-key: osip.sysu.received
    req:
      queue-name: req
      exchange-name: osip
      routing-key: osip.req.received
    res:
      exchange-name: osip
    upd:
      queue-name: upd
      exchange-name: osip
      routing-key: osip.upd.received
