eureka:
  client:
    healthcheck:
      enabled: true

owms:
  partners:
    sps01: tcpip-palett1
    sps02: tcpip-palett2

---
spring:
  profiles: ASYNCHRONOUS

owms:
  driver:
    osip:
      enabled: true
    locu:
      queue-name: locu
      exchange-mapping: locu.*
    sysu:
      queue-name: sysu
      exchange-mapping: sysu.*
    req:
      queue-name: req
      exchange-mapping: req.*
    res:
      exchange-mapping: res.*
    upd:
      queue-name: upd
      exchange-mapping: upd.*
